language: go

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - go get github.com/golang/lint/golint
  - go get github.com/go-task/task/cmd/task

script:
  - task qa
  - task coveralls

go:
  - 1.7.x
  - 1.8.x
  - tip
